loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  limits_config:
    # Should be default in 3.0 but who knows.
    allow_structured_metadata: true
    # These are bad limits, 0 permits unlimited except for ingestion rates
    max_global_streams_per_user: 0
    ingestion_rate_mb: 999999
    ingestion_burst_size_mb: 9999999
  tracing:
    enabled: true
  querier:
    max_concurrent: 4


gateway:
 ingress:
   enabled: true
   hosts:
     - host: loki.sparks.com
       paths:
         - path: /
           pathType: Prefix
         - path: /otlp
           pathType: Prefix
           service:
              name: loki-backend
              port: 3100
         - path: /grpc
           pathType: Prefix
           port: 4317

deploymentMode: SimpleScalable

backend:
  replicas: 3
  affinity:
  podAntiAffinity: null
read:
  replicas: 3
  affinity:
  podAntiAffinity: null
write:
  replicas: 3
  affinity:
  podAntiAffinity: null
minio:
  enabled: true
  # Required if installed in single namespace
  serviceAccount:
    create: false
    name: loki-minio-sa
  persistence:
    size: 50Gi
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0