gateway:
  enabled: true
  ingress:
    enabled: true
    tls: []
    hosts:
      - host: tempo.sparks.com
        paths:
          - path: /
            pathType: Prefix
storage:
  trace:
    backend: s3
    s3:
      access_key: 'grafana-tempo'
      secret_key: 'supersecret'
      bucket: 'tempo-traces'
      endpoint: 'tempo-minio:9000'
      insecure: true

minio:
  enabled: true
  mode: standalone
  rootUser: grafana-tempo
  rootPassword: supersecret
  # Required if installed in single
  serviceAccount:
    create: false
    name: tempo-minio-sa
  buckets:
    - name: tempo-traces
      policy: none
      purge: false

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
